### ISSUE TITLE
issue for installing helk on ubuntu 16.04 

### ISSUE THREAD

**Issue by Gourav1990** [Cyb3rWard0g/HELK#12]
Hello, 
my name is Gourav  and i have a problem facing for installing helk  so please give me the solution for the issues  
1. i am trying to install helk on an ubuntu machine 16.04 version i am get stuck at running the jupyter server. can you help me to resolve this issue 
![helk11](https://user-images.githubusercontent.com/35369246/34873137-f37f074a-f7b9-11e7-9c74-61012d5bdcb9.PNG)

**Comment by WasKa001** [comment]
@Gourav1990 try selecting option 3 (installation from local bash script) and let us know if you'll encounter the same error during installation

**Comment by CrazyLlama** [comment]
Very strange but I had the same issue on both 1 and 2, tried it with 3 and it still got stuck at the same point. On cancelling and retrying it everything went through fine? 😕 

I'll have a look and see if everything is running properly and see if I can find where the issue is, may just be a minor incompatibility.

**Comment by CrazyLlama** [comment]
Yep, appears to have given me a false success message:

``` bash
**********************************************
**           HELK - M E N U                 **
**                                          **
** Author: Roberto Rodriguez (@Cyb3rWard0g) **
** HELK build version: 0.9 (BETA)           **
** HELK ELK version: 6.x                    **
** License: BSD 3-Clause                    **
**********************************************

1. Pull the latest HELK image from DockerHub
2. Build the HELK image from local Dockerfile
3. Install the HELK from local bash script
4. Exit

[HELK-INSTALLATION-INFO] Enter choice [ 1 - 4] 3
[HELK-INSTALLATION-INFO] Checking local vm.max_map_count variable and setting it to 262144
[HELK-BASH-INSTALLATION-INFO] Installing the HELK from local bash script
[HELK-BASH-INSTALLATION-INFO] This is not a debian-based system..
[HELK-BASH-INSTALLATION-INFO] Install docker in your system and try to use one of the HELK's docker options..
[HELK-INSTALLATION-INFO] Obtaining current host IP..



***********************************************************************************
** [HELK-INSTALLATION-INFO] YOUR HELK IS READY                                   **
** [HELK-INSTALLATION-INFO] USE THE FOLLOWING SETTINGS TO INTERACT WITH THE HELK **
***********************************************************************************

HELK KIBANA URL: http://10.0.0.28
HELK KIBANA USER: helk
HELK KIBANA PASSWORD: hunting
HELK JUPYTER CURRENT TOKEN:  First, run the following: source ~/.bashrc && pyspark
HELK SPARK UI: http://10.0.0.28:4040
HELK JUPYTER NOTEBOOK URI: http://10.0.0.28:8880


IT IS HUNTING SEASON!!!!!
```
Both of these return nothing also:

``` bash
# lsof -i:8880
# lsof -i:4040
```

I'll have a nosy through the install file manually also!

**Comment by CrazyLlama** [comment]
Removing and re-downloading the packages/HELK appears to a fixed this issue - I can't really say much beyond that. Apologies!

**Comment by Cyb3rWard0g** [comment]
@Gourav1990 thank you for sharing the details of your install. can you provide the output of /var/log/helk-install.log ?? Usually the Jupyter server parts takes a little bit to finish. However, I would like to see what you got in the HELK installation logs. Thank you

**Comment by Cyb3rWard0g** [comment]
@CrazyLlama thank you for sharing what worked for you. However, I have a question. The bash script is limited to only work with debian systems. I see you got the [HELK-BASH-INSTALLATION-INFO] This is not a debian-based system.. message. When you ran the script again, did you use the same system? what OS, distribution and version are you running the HELK on? The details help the HELK to be better and compatible. Let me know. thank you!

**Comment by CrazyLlama** [comment]
Haha - I accidentally built a centos 7 system which would have been my issue, I rebuilt into Ubuntu 16.04 and all works fine. (I say accidentally as I was spinning this up into VMs to play with it.)

**Comment by Cyb3rWard0g** [comment]
@CrazyLlama Awesome! thank you for letting me know. from the image that you shared, you used the bash script option and failed which would make sense if you were using a Centos 7. If you rebuilt it and then tried option 1 and 2, and it worked fine it is because you are installing Docker and then on the top running a container from an Ubuntu image. In other words, if you would have kept your Centos 7 and run option 1 and 2, you would have been fine. However, with your Centos 7, you were running the bash script that is compatible only with Debian systems. Let me know if this make sense and if you could please let me know if you have any other issues. Thank you @CrazyLlama ! All this helps to improve the installation piece of the HELK. I will make the script stop when it recognizes it is not a debian system instead of jumping to the last message.

**Comment by Cyb3rWard0g** [comment]
Good morning @Gourav1990 . Let me know if you were able to finish the HELK installation. Were you able to get all the options running?

**Comment by Gourav1990** [comment]
Hello,

Installation work is going on when the installation is finish then i let
you know

**Comment by Cyb3rWard0g** [comment]
Thank you @Gourav1990 . Let me know 👍

**Comment by Cyb3rWard0g** [comment]
@Gourav1990 were you able to successfully install the HELK ?? Thank you

**Comment by Cyb3rWard0g** [comment]
@Gourav1990 let me know if you still have any issues.
