### ISSUE TITLE
Kibana - Warning (No cached mapping for this field.

### ISSUE THREAD

**Issue by rangerrkm** [Cyb3rWard0g/HELK#139]
Hello, 

I have setup HELK and have been performing some testing and have noticed that I have a warning on 3 fields. On the Global Dashboard
Error: No cached mapping for this field. Refresh field list from the management > Index Patterns page.

I have done this many times without resolve, does anyone else have this same issue.

z_logstash_pipeline
z_logstash_type
z_original_message

Thanks,

**Comment by Cyb3rWard0g** [comment]
Good morning @rangerrkm ! Those fields are not searchable. Those fields are stored but they are not indexed. when you say that you have 3 warning on the Global Dashboard, do you mean on the visualizations or in the Discover view added to the dashboard? I asked this because there are not visualizations that take those 3 fields that you mention. Also, those three fields are defined in the output templates: https://github.com/Cyb3rWard0g/HELK/blob/master/docker/helk-logstash/output_templates/10-logs-all-default.json#L45 . The fields are not enabled as you can see. You can read more about it here: https://www.elastic.co/guide/en/elasticsearch/reference/current/enabled.html . Let me know if this helps 👍

**Comment by neu5ron** [comment]
Great question, and as Roberto mentioned - these fields are not indexed but only "stored". They are for troubleshooting and for chain of custody ("z_originaL-message"). Since they are limited use case in actually analysis, we are setting them as non-indexed to reduce storage space.

**Comment by Cyb3rWard0g** [comment]
Thank you for the confirmation @neu5ron . Closing this issue since the question has been answered already. @rangerrkm feel free to re-open this issue if our responses did not answer your question. Thank you!
