### ISSUE TITLE
SparkContext doesn't appear to be present after install on ESXi

### ISSUE THREAD

**Issue by wesleyraptor** [Cyb3rWard0g/HELK#17]
I installed this in AWS the other day with no issues. Trying to install on ESXi in a virtual lab and I've hit a snag twice in a row now where the Spark UI doesn't come up. I don't think it's an environmental issue - DNS, HTTP, and HTTPS all work. Did not see any errors whatsoever in the helk-install log. 

Installed on Ubuntu Server 16.04.2 amd64 xenial VM. Pulled the image from dockerhub and ran it per the install script. I'm getting Kibana UI and Jupyter notebook (ports 80 and 8880 respectively) but nothing on 4040 for the Spark UI. I looked in the container and noticed the ESXI deployment was missing this process: 

AWS:
![image](https://user-images.githubusercontent.com/16872121/35038780-b02bcff8-fb30-11e7-9a7f-6587b712f3fe.png)

I tried to run the command verbatim on my ESXI deployment inside the container and got this stack trace:
![image](https://user-images.githubusercontent.com/16872121/35038883-0be1918e-fb31-11e7-85ab-1214322378cd.png)

I don't have much experience with Spark so there's a chance I'm way off. I guess my question is has anyone had success installing on a VM in ESXI? Thanks!

**Comment by Cyb3rWard0g** [comment]
Good morning @wesleyraptor , when you installed the image in AWS, did you test the Jupyter Notebook first (opening the one I created) before accessing the UI on port 4040??. If so, I think the issue is that when there are no kernels initiated (spark and Jupyter working together), Spark context does not get initiated. When you installed it in ESXI, did you go straight to the Spark UI?? Did you open the Jupyter notebook I have in the repo first?? I think that would be a first step to troubleshoot this issue. Also, can you try to install the HELK via the DockerFile. Let me know if you have the same issues with it. I will take a look at the PYSPARK_DRIVER_CALLBACK_HOST error that you have too. thank you.

**Comment by wesleyraptor** [comment]
Loading the sparkcontext object in the notebook solved the problem. Sorry for my ignorance!

**Comment by Cyb3rWard0g** [comment]
@wesleyraptor not at all man. It is all good. It is actually my fault for not adding that detail to it. I am also learning Spark as I go and I didnt pay attention to that extra step that needs to happen to enable the Spark Context. I will add that in the section where I provide information about the Spark UI. I will add "before accessing the Spark UI, make sure you start a new jupyter notebook or run the "Check_Spark_Graphframes_Integrations.ipynb" notebook". "That should start spark and spark context" (Spark-Jupyter Integration). Thank you for your help on this one too and for helping the project update its documentation) 👍  . @wesleyraptor I would like to also hear more about your use cases with the HELK and help in any way I can if needed.

**Comment by Cyb3rWard0g** [comment]
Added Spark UI details in the Installation section of the Wiki: https://github.com/Cyb3rWard0g/HELK/wiki/Installation Thank you @wesleyraptor ! 👍
