### ISSUE TITLE
Question: Installation Questions (RHEL)

### ISSUE THREAD

**Issue by lostInSpaceSomewhere** [Cyb3rWard0g/HELK#174]
**Question on Installation of HELK - in particular RHEL installation**
*i have been given a new RHEL server to install HELK on.  i have a few questions to ensure i not only install the product properly but also allocate resources on the server properly.*

1. What is the installation directory of the application
2. where does the database sit

The script looks at my var-root volume for understanding available storage space

3. are there any unique permissions for SELinux needed, especially around any web based applications?
4. what package repositories are needed for RHEL to be made available?

I'm sure there will be more but off the top of my head all i can think of for the moment.

**Comment by neu5ron** [comment]
glad to hear someone else is using it on RHEL & SELinux, I know what that means :)
1. everything gets built out of wherever you clone (or move the cloned) HELK directory
2. the docker containers all sit in /var/lib -- without having to do any ln's or edit the yamls to change storage directory - build your server to give as much space as you can to /var/lib
3. I am not specifically sure, I know it shouldn't be "too" difficult and it appears that @borbelyau has done this, @borbelyau do you think you could drop in the selinux modifications you made to get HELK working? I don't have the cycles to test and post. Thanks!!!
4.  agian, if @borbelyau could help that would be awesome -- i know docker package repo (make sure it is installing docker 18+, it will have to hit github (temporarily, don't allow that forever), you will have to modify firewalld to allow 443, 9092

feel free to keep asking questions, and please drop in any information and configs so that we can update and add the FAQ for those who may also want to install HELK with SELinux.

**Comment by lostInSpaceSomewhere** [comment]
if you dont mind, ill ask my questions here as i go through this.
first issue is when it checks the distribution list, which i'm guessing doesn't have anything for RHEL.
```
[HELK-INSTALLATION-INFO] Checking distribution list and product version
./helk_install.sh: line 103: ee_notice: command not found
```

**Comment by neu5ron** [comment]
fyi, have to preface this isnt supported for now - but just helping:
I would recommend removing “rhel” from line 102 and adding it to line 97 so
that line 97 looks like:
centos|rhel)
and line 102 looks like
ol|sles)

I will revisit this in the next week or so for the actual code, because
technically centos&rhel are pretty much the same - but im not sure of with
the whole rhel docker thing of podmam and what not - so we will have to
see...

**Comment by lostInSpaceSomewhere** [comment]
Fix above got me past the initial headache - thank you!

**Installing htpasswd error**
looks like when installing some dependencies for httpd tools it prompts for interactions
from the logs:
``` Is this ok [y/d/N]: Exiting on user command ```

**Comment by mspotlight** [comment]
@lostInSpaceSomewhere Did you ever resolve this docker issue? I am running into the same problem. TIA!

**Comment by lostInSpaceSomewhere** [comment]
@mspotlight 
I had my linux team set DOCKER EE to my host.
I know you can install a previous version of docker CE to RHEL but it wont be the most current.  This also limits the user on teh docker-compose version to v 2 (or at least i couldnt get v3 installed).
im testing building out this with docker ee.

**Comment by neu5ron** [comment]
fixed in https://github.com/Cyb3rWard0g/HELK/pull/415
