### ISSUE TITLE
[Cloud] HELK Terraform Scripts

### ISSUE THREAD

**Issue by Cyb3rWard0g** [Cyb3rWard0g/HELK#208]
Prototype initial terraform integration

**Comment by OliverMorenoGonzalez** [comment]
Hello,
How are you testing each Cloud?
Or are you testing in local Kubernetes?

**Comment by Cyb3rWard0g** [comment]
I am testing each cloud via the aws provider and azure provider. Not testing via kubernetes yet.

**Comment by OliverMorenoGonzalez** [comment]
I asked because I saw some tech that could be usefull to test different Cloud.

Repository Go Cloud from Google, It is like generic interfaces for common use cases, with one interface you access to different Cloud providers.

I haven't tried yet but I hope test it (in near future).

I hope we can share info about Cloud, because this is new for me.

**Comment by apolloclark** [comment]
I can help you with the Terraform scripts on AWS. I have the entire Elastic stack w/ Packer AMI builds, with each layer in a different Autoscaling Group.

https://github.com/apolloclark/tf-aws/tree/master/aws-ec2/terraform

email me at apolloclark@gmail.com to discuss details

**Comment by Cyb3rWard0g** [comment]
🌶 🔥 @apolloclark !!! Thats awesome. I remember we talked a while back about some of that. It would be great to have your help on that. I am just learning terraform and I have a long way to go after reading some of your configs today lol. I will e-mail you in a few. Thank you for willing to help in this area 👍 Looking forward to it!

**Comment by apolloclark** [comment]
@Cyb3rWard0g email me when you get a chance, I have some details to discuss. :)

**Comment by Cyb3rWard0g** [comment]
Moved to AWS CloudFormation Templates in the roadmap
