### ISSUE TITLE
Must be root to run install script

### ISSUE THREAD

**Issue by jermdw** [Cyb3rWard0g/HELK#21]
Hey @Cyb3rWard0g! Currently, you must be the root user to use the `HELK_INSTALL.sh`. 

I believe with a few modifications, this is avoidable. Specifically when it comes to operations on docker containers. If docker is installed and configured properly, the current user will be a member of the `docker` group and thus be able to perform container operations without invoking `sudo`.

There are a few parts of the install script that are a bit more problematic but should be avoidable. I can submit some PR's with a few modifications if you think this is a good idea. I just feel icky running scripts as `root`.

**Comment by Cyb3rWard0g** [comment]
Hey @jermdw !!! Yes that would be great! If you can help to explore the option of running them without being root, it would be great. I have considered that change, so it will help a lot. Let me know 👍  Thank you man!

**Comment by Cyb3rWard0g** [comment]
Hey @jermdw ! I updated the build to run most of the containers with a non-root account. The only container running as root is the Jupyter one and it is because it is a little complicated to set up all the dependencies for Jupyter hub and spawn new processes as other users with a regular use account. I will close this issue when I figure that our. Keeping you in the loop 👍

**Comment by Cyb3rWard0g** [comment]
Hey @jermdw closing this issue since all the containers that are build by me are not running as root. Thank you for the suggestions 👍 I hope all is well man.
