### ISSUE TITLE
Error: Could not run HELK via docker-compose file helk-kibana-notebook-analysis-basic.yml (Error Code: 1)

### ISSUE THREAD

**Issue by ehsanshaikh77** [Cyb3rWard0g/HELK#224]
Please see this error @Cyb3rPanda @Cyb3rWard0g . helk-install.log snapshot is also attached.
What should I do now to solve this error?
![image](https://user-images.githubusercontent.com/26488637/54938785-e59caa00-4f48-11e9-89a7-a3c7af6ab945.png)
![image](https://user-images.githubusercontent.com/26488637/54938818-f4835c80-4f48-11e9-81f2-e145ec6a1577.png)

**Comment by neu5ron** [comment]
did you try running it again? I think elastic's docker images were under maintenance for a brief while

**Comment by ehsanshaikh77** [comment]
Yes I tried it, it was giving same type of error which I mentioned earlier

Sent from Yahoo Mail on Android 
 
  On Tue, 26 Mar 2019 at 8:27 AM, Nate Guagenti<notifications@github.com> wrote:   
did you try running it again? I think elastic's docker images were under maintenance for a brief while

**Comment by Cyb3rWard0g** [comment]
Hey @ehsanshaikh77 I think you should open an issue with Kibana github docker repo. we cannot control when the image is available or not. I really do not know why your kibana is failing. Maybe in the official Kibana docker github repo , they can help why their docker registry is not available when you try to download that image. I do not manage that Image. All I do is I point to it. I am closing this issue because we do not manage or handle that image. Elastic does.

**Comment by PIBempos** [comment]
I had the same error, my problem was that I am behind a proxy andaving the proxy exported to the environment  variables and git was not enough. I have added the proxy in the configuration as per the guide bellow and it works:

https://stackoverflow.com/questions/23111631/cannot-download-docker-images-behind-a-proxy
