### ISSUE TITLE
HELK server quits working with internal server errors after a few days.

### ISSUE THREAD

**Issue by Cooldog1099** [Cyb3rWard0g/HELK#249]
I know HELK hasn't been tested with large data sources, so I figured I would try. I am sending it roughly 15 million events a day, but after a few days internal server error start showing on the Kibana web page. The OS has plenty of RAM, CPU, and SSD space. Is anyone anyone aware of an upper limit for the number of events or any optimizations I could try?

Thanks!

**Comment by Cyb3rWard0g** [comment]
Hey @Cooldog1099 , Can you share any logs from ES when that happens?

**Comment by Cooldog1099** [comment]
Sure. What logs do you want to see?

**Comment by Cyb3rWard0g** [comment]
hey @Cooldog1099 , sorry for the late response. You say that you see an server error start on the Kibana Web page. Can you share the Kibana and Elasticsearch logs they that happens?

` sudo docker logs --follow helk-elasticsearch`
`sudo docker logs --follow helk-kibana`

Thank you. Also, have you tried the latest version? thank you in advance.

**Comment by neu5ron** [comment]
@Cooldog1099 if this is still an issue, repopen the issue and perform the following:  

1) send the output of `df -h`  
seems to me that one of the partitions is full.. unfortunately (most) OS' give `/var` their own partition with limited disk space.. and because the docker images all live under `/var/lib` this can be an issue.
2) output of the commands @Cyb3rWard0g mentioned in the previous comment on this issue
