### ISSUE TITLE
Filebeat to logstash logs ingestion

### ISSUE THREAD

**Issue by moosa-aslam** [Cyb3rWard0g/HELK#276]
Dear Team,

I managed to ingest Linux OS logs from filebeat to kafka. but I am unable to ship logs from kafka to logstash. I am attaching the filebeat.yml file for reference. our team had no issues with winlogbeat when shipping logs from windows to logstash.
[filebeat.yml.txt](https://github.com/Cyb3rWard0g/HELK/files/3270624/filebeat.yml.txt)

**Comment by Cyb3rWard0g** [comment]
The Logstash Input should read it fine https://github.com/Cyb3rWard0g/HELK/blob/master/docker/helk-logstash/pipeline/0002-kafka-input.conf#L9 . Do you see any error messages in the broker?

The issue that I see is that from Logstash Input, it will make it to https://github.com/Cyb3rWard0g/HELK/blob/master/docker/helk-logstash/pipeline/9998-catch_all-output.conf since HELK does not have a specific OUTPUT for Filebeat as a whole. the project has one specific output but for OSQUERY logs which was added by @richiercyrus : https://github.com/Cyb3rWard0g/HELK/blob/master/docker/helk-logstash/pipeline/9958-osquery-output.conf 

You filebeats logs should had been caught by the catch all output config https://github.com/Cyb3rWard0g/HELK/blob/master/docker/helk-logstash/pipeline/9998-catch_all-output.conf

**Comment by moosa-aslam** [comment]
I followed your blogspot thread and found this 
"Data gets collected with Winlogbeats (Only shipper supported for now"

Reference :
https://cyberwardog.blogspot.com/2018/04/welcome-to-helk-enabling-advanced_9.html

I will soon post my configs as you have mentioned above . another question how to check kafka broker for error messages.

**Comment by moosa-aslam** [comment]
I am trying to ship Linux OS audit logs to helk. According to HELK architecture the logs should be shipped in following order.
Filebeat>Kafka>Logstash>Elasticsearch

I have uploaded 2 files 
1- etc/filebeat/filebeat.yml
2- docker/helk-logstash/config/logstash.conf (which I created myself) there.

[filebeat.yml.txt](https://github.com/Cyb3rWard0g/HELK/files/3290178/filebeat.yml.txt)
[logstash.conf.txt](https://github.com/Cyb3rWard0g/HELK/files/3290179/logstash.conf.txt)

**Comment by moosa-aslam** [comment]
I am trying to ship Linux OS audit logs to helk. According to HELK architecture the logs should be shipped in following order.
Filebeat>Kafka>Logstash>Elasticsearch

I have uploaded 2 files
1- etc/filebeat/filebeat.yml
2- docker/helk-logstash/config/logstash.conf (which I created myself) there.

[logstash.conf.txt](https://github.com/Cyb3rWard0g/HELK/files/3290208/logstash.conf.txt)
[filebeat.yml.txt](https://github.com/Cyb3rWard0g/HELK/files/3290209/filebeat.yml.txt)

**Comment by Cyb3rWard0g** [comment]
Use a similar filebea file like this: https://github.com/Cyb3rWard0g/HELK/blob/master/filebeat/filebeat.yml . In yours, you are forgot to comment the Elasticsearch output.

For Logstash, 
you will just have to find a field and value that allows you to identify you data specifically. For example, the filebeat topic in Kafka is also used by users that want to consume Osquery data. Therefore, the Osquery logstash output config is the following:
```
output {
  if [source] == "/var/log/osquery/osqueryd.results.log"{
    elasticsearch {
      hosts => ["helk-elasticsearch:9200"]
      index => "logs-endpoint-osquery-%{+YYYY.MM.dd}"
      document_id => "%{[@metadata][log_hash]}"
      user => 'elastic'
    }
  }
}
```
Find a field like `source` to identify your data.

**Comment by Cyb3rWard0g** [comment]
Hey @moosa-aslam , please let me know if you were able to test the configs I shared. thank you!

**Comment by moosa-aslam** [comment]
@Cyb3rWard0g Robert I will get back to you shortly I am away from my testing lab these will update you asap.

**Comment by Cyb3rWard0g** [comment]
Closing this do to inactivity. nothing to fix and custom build.
