### ISSUE TITLE
Date parsing for year in 11-winevent-sysmon-filter.conf is incorrect

### ISSUE THREAD

**Issue by tdesrochers** [Cyb3rWard0g/HELK#30]
In 11-winevent-sysmon-filter.conf the year parcing is `YYYY` when elasticsearch docs state year is `yyyy`.  Not sure if this will throw a date parse failure error for you or now.

https://www.elastic.co/guide/en/logstash/current/plugins-filters-date.html

```

y | yearyyyyfull year number. Example: 2015.yytwo-digit year. Example: 15 for the year 2015.
-- | --


```

**Comment by Cyb3rWard0g** [comment]
Hey @tdesrochers ! Thank you for pointing that up. It does not throw a date parse failure error message. 

![image](https://user-images.githubusercontent.com/9653181/37037377-2572ed18-2120-11e8-97f3-3e050755aee5.png)

However, I will keep that in mind for the next update and test it with lowercase "y" too. I want to make sure the configs are following the right syntax. I expect nothing to change since it is working fine the way it is now. I did not notice that when I was reading the date filter docs. Thank you again. I hope you have a good rest of the week 👍

**Comment by Cyb3rWard0g** [comment]
Hey @tdesrochers ! I did some reading about the [Date filter](https://www.elastic.co/guide/en/logstash/current/plugins-filters-date.html) and [Joda-Time Documentation](http://www.joda.org/joda-time/key_format.html) and the YYYY is also allowed and parsed properly by Elasticsearch. The only difference between symbol "Y" (Year of era) and "y" (year) is that values of **Y** (**YearOfEra**) are always positive and never zero or negative values. **y** (**Year**) on the other hand can represent previous eras (i.e BC) with negative values. **YearOfEra** values can represent previous eras too but with positive values (i.e. 1 for 1BC/BCE, 2 for 2BC/BCE). Both symbols **Y** and **y** can be used when dealing with positive values for year fields. I dont think I will be parsing logs from previous eras or expecting to show negative values as part of timestamps for event logs. I learned something new tonight 👍 . I will close this issue since there is nothing to fix in the parsers. Thank you again!
