### ISSUE TITLE
Include elastalert kibana plugin

### ISSUE THREAD

**Issue by Trolldemorted** [Cyb3rWard0g/HELK#306]
What do you think of including the [kibana plugin for elastalert](https://github.com/bitsensor/elastalert-kibana-plugin)?

**Comment by neu5ron** [comment]
seems awesome, however with that said - as we have had issues with 3rd party plugins (even Elastalert itself) in relation to upgrading the ELK stack.
Do you know if this supports the latest Elastalert always? Also, I have noticed any Kibana plugins usually do NOT do well with new versions of Kibana (but that depends on the Developer and their time to update).. 
Have you tested this in Kibana 7 (latest version of HELK)?

**Comment by Cyb3rWard0g** [comment]
it seems that the plugin is up to date: https://github.com/bitsensor/elastalert-kibana-plugin/releases

However,  I believe we need to track how long it takes for them to keep up with Elastic updates. I agree with @neu5ron , sometimes it can slow down latest updates.

**Comment by Cyb3rWard0g** [comment]
Even though the plugin says compatibility for 7.2 and higher, it does not seem to be constantly updated with latest version. that will be a problem to keep a working stack for stable version. I believe this will fall on custom build setup. Closing this since it will not be added at the moment. thank you for the suggestion @Trolldemorted
