### ISSUE TITLE
use sentinl instead of elastalert

### ISSUE THREAD

**Issue by ssi0202** [Cyb3rWard0g/HELK#31]
hi just an idea 

the sentinl guys support the latest elk versions

https://github.com/sirensolutions/sentinl

i've started to amend the logstash filters on my repositiory, but work is slow as i have a do my "normal" tasks at work also. but im trying to give it priority when i can

im working on adding firewall and network logs and updating sysmon etc with the event id's i shared earlier.

reguarding the integration of bro have you seen the security onion project they in the process of adding elk functionality so you might want to take a look at what they are doing, already could save you some time. i run security onion in prod and are very pleased with it, the prospect of adding elk and sentinl alerting is on my road map

**Comment by Cyb3rWard0g** [comment]
Hey @ssi0202 !! Awesome!! last time I checked, it was not compatible with the latest version. Thank you for sharing. Regarding SecurityOnion, it is a great NSM project and I have heard good things about it. I am working with @neu5ron (Nate) to have all the bro stuff in HELK too. There a few things we will be doing differently but it is a great reference. Also ROCK NSM is a great reference for all that. I will take a look at Sentinl too 👍 Thank you

**Comment by neu5ron** [comment]
Sentinl is very cool, also Kibi and some other great projects have extended Kibana and Elasticsearch features.
However, they tend to break with each Elastic upgrades. Our goal is to not stray far from the Elastic branch so we can perform continous upgrades/updates along with Elastic’s repo.
Also, when Kibana 7 and such is GA release a lot more from the plugin community should be able to be supported (hopefully).

Regarding Bro/NSM:
In the near future we plan on leveraging RockNSM for their Bro and NSM deployments. That could change - but our goal is to continue to provide endpoint related threat hunting and ELK build. Otherwise we are reinventing if we don’t leverage Rock NSM, Security Onion, or the like.

**Comment by Cyb3rWard0g** [comment]
I agree with @neu5ron ! There was another request to use Search Guard also to allow authentication and index permissions, but usually with a major Elastic update, it breaks :( . This is why I also think we should wait a little bit and use whatever Elastic has on the roadmap for the basic subscription. I will close this, but it will be on tto-do list as a potential integration in the future.
