### ISSUE TITLE
Uninstall/remove containers is deleting EVERYTHING

### ISSUE THREAD

**Issue by gvsrini** [Cyb3rWard0g/HELK#316]
I had a few other dockers for monitoring my server and this script deleted just about everything. Pls ensure that you only delete HELK images and containers and not ALL docker containers.

**Comment by Cyb3rWard0g** [comment]
Thank you for letting us know about it. Even though I always recommend to install HELK on its own box due to resources constraints and also check the code before running Alpha version scripts (not production ready at all), I believe it is important for the scripts we provide to be very specific when performing a task. In this case removing containers and images should be only applied to HELK containers and images. I agree with you 100%. Im sorry for the inconvenience. I am pushing a hot-fix right now. Thank you for bringing this up.

**Comment by nugnugrawk** [comment]
how to connection log windows (client) to HELK in ubuntu ?
