### ISSUE TITLE
Feature Request: Create or use an easier method to manage Sigma rules

### ISSUE THREAD

**Issue by webhead404** [Cyb3rWard0g/HELK#360]
HELK could benefit from a better way to manage Sigma rules such as https://github.com/defensivedepth/playbook or https://github.com/socprime/SigmaUI.

**Comment by Cyb3rWard0g** [comment]
Hey @webhead404 , can you provide more details how those two projects would help?
- Playbook: It is not clear what it does
- SigmaUI would only allow you to get existing and translate them to a few backends. That does not manage elastalert rules. 

Can you provide also some more details when you say an easier way to manage elastalert rules?

**Comment by neu5ron** [comment]
@webhead404 thanks for opening.

@Cyb3rWard0g yeah atleast at a minimum may be good to have ability to add rules and elastalert/watcher dynamically load/use the new rule - even if its just something simple like adding the new sigma rule to the rule/path and elastalert consumes it and adds it

**Comment by Cyb3rWard0g** [comment]
ahh ok! yeah, Im more interested in the webhook to interface with Elastalert than the rest. However, I believe adding the whole app just to translate Sigma to Elastalert and give me an interface to see them, I dont know if it would be worth to have that extra dependency just for that. It would be good to POC it! I just want to be careful because we have seen it with Bitsensor Elastalert UI and others falling behind when ELK updates or other dependency and holds other features that I believe have priority. I think it would be good to keep this open and have a POC available in the documentation. As any other update added HELK, I will wait until it is more mature too imo. Thank you very much for sharing @webhead404 ! I appreciate it

**Comment by Cyb3rWard0g** [comment]
Not in the roadmap at the moment.
