### ISSUE TITLE
add custom data from filebeat [json]

### ISSUE THREAD

**Issue by omrirefaeli** [Cyb3rWard0g/HELK#383]
Hey :)
I am trying to add data from a script I wrote on a Windows computer to HELK. I saved the data in a JSON format.
I wrote a special .conf file to put in the logstash's conf.d folder (pipeline in HELK), but I don't have write permissions to the /opt/logstash/pipeline (/usr/share/logstash/pipeline) folder where all of the conf files are. (attached)
![image](https://user-images.githubusercontent.com/30568019/69720736-f6c33980-111b-11ea-9ce9-50a09f05a8dc.png)
I am guessing user 1001 is the one who created this folder in the docker setup, and the user probably got deleted.
sudo is not installed, afraid to use apt inside the docker, I also don't even know the 'logstash' password.
I set up an external logstash instance myself trying to send the data over to the HELK docker but elasticsearch docker doesn't listen to host's port 9200, so it didn't work too.
![image](https://user-images.githubusercontent.com/30568019/69721435-82899580-111d-11ea-96e2-31bd5643385b.png)

I am working in an AWS environment with EC2s instances.

p.s. Kafka didn't work for me, so I am sending it directly to logstash on port 5044 ( working with the  default Windows logs).

conf file:
![image](https://user-images.githubusercontent.com/30568019/69721085-be702b00-111c-11ea-85f9-68f2ba71350d.png)

thank you for your help & work, really appreciated!!

**Comment by Cyb3rWard0g** [comment]
the pipeline is mounted from local HELK/docker/helk-logstash/pipeline. You have to make the changes on the host (i.e Ubuntu box) and not on the helk-logstash container. let me know if that helps. i would do the following:
- docker stop helk-logstash
- locally on the git folder HELK go to HELK/docker/helk-logstash/pipeline
- add your custom .conf to that folder (i.e HELK/docker/helk-logstash/pipeline)
- docker start helk-logstash

Let me know if that works. You cannot update .conf files inside of the helk-logstash container.

**Comment by omrirefaeli** [comment]
Thank you very much for your time and comment.
it worked perfectly, the conf file is installed inside the docker.
now I just have to play with it a bit to create my own index.

however, the entire thing popped an important question for me. if at some point, I would like to use multiple logstashes, also from an external logstash ( which I tried in this case), is there a way to send the logs to HELK? Helk does not tunnel port 9200 from host to helk-elasticsearch..
Thanks again!

**Comment by Cyb3rWard0g** [comment]
Awesome I am glad the Logstash configs work. yeah you can update the whole pipeline locally, and it would work. Regarding exposing ES on port 9200, the project does not recommend to do that, but it is definitely possible. All you have to do is add the following lines with ports `9200:9200` under the Elasticsearch container in your docker-compose file

https://github.com/Cyb3rWard0g/HELK/blob/master/docker/helk-kibana-analysis-alert-basic.yml#L43-L45

I am closing this issue since it solve your initial problem. Thank you for using and testing the project. Please let me know if you have any other questions. You can open a new issue for the ES 9200 if you go that route. It should be a simple fix.

**Comment by omrirefaeli** [comment]
A hero. Thanks a lot!
