### ISSUE TITLE
docker kafka-broker and  ksql restarting continues

### ISSUE THREAD

**Issue by linuxesabz** [Cyb3rWard0g/HELK#401]
i install centos 7
and install helk 
selinux is disabled
but when i execute docker ps -- status kafka-broker and ksql is restarting and container is not runing
log /var/log/helk-install.log not showing error

**Comment by troplolBE** [comment]
hi @linuxesabz !

I have the same issue with my CentOS 7 machine. Can you just make sure to proviude everything that is asked by the issues template so that the authors can win time by directly investigating the logs ? If you want to take a look a my issue and compare with your problem it is this one #388.

**Comment by neu5ron** [comment]
closing, please add notes to #388
CentOS compatibility has been merged, please test new build and add notes there
https://github.com/Cyb3rWard0g/HELK/pull/415
