### ISSUE TITLE
Overlapping Networks

### ISSUE THREAD

**Issue by TDominiqueWilliams** [Cyb3rWard0g/HELK#43]
When trying to install HELK with `sudo ./helk_install.sh` the script errors when attempting to deploy docker-compose.yml. The error came back with `* ERROR: Could not run HELK via docker-compose (Error Code: 1).` After investigating the logs, `Creating network "helk_helk" with driver "bridge"
cannot create network 8320bb7d24b22f724839bb65351a3ee058a06a8dc5bb549e14e060cbf5aa5746 (br-8320bb7d24b2): conflicts with network 2e2869986edfcee84d6dd7208ac357a032cc2da1d70f45d5141ba1c49e9f4d37 (br-2e2869986edf): networks have overlapping IPv4`

After changing the networks to `10.18.0.X` and the subnet `10.18.0.0/24`. I am not entirely sure if the network overlap error is due to the wide subnet, but it temporarily repairs the issue.

**Comment by Cyb3rWard0g** [comment]
hey @TDominiqueWilliams ! Interesting. I dont know why there would be another network overlapping with the static configuration. I will try to remove the IPv4 portion of the config and run it without it. I will push an update soon. I will test it without the IPv4 features. I am using the containers names to connect to each other so it should work without the IP addresses. I just have to test the Jupyter notebooks since they point to elasticsearch IP address.

**Comment by TDominiqueWilliams** [comment]
When I attempt to change the environment back, I get an all-new error. I have attached the screenshot. This was after I did a fresh install
![image](https://user-images.githubusercontent.com/24858059/38740467-aa0a2c78-3f05-11e8-952b-59b46a012abb.png)

**Comment by Cyb3rWard0g** [comment]
ok thank you. Did you install HELK in a fresh host install? Also, did you have docker installed already in the box?? or the instal script installed docker?

**Comment by TDominiqueWilliams** [comment]
It is a fresh install on a VM image with docker already installed.

**Comment by Cyb3rWard0g** [comment]
Ok. i had a similar issue with a friend that had docker already installed. I wonder if already created another bridge network or a similar config such as the one from HELK. Would you mind uninstalling that docker version and just let the script install docker for you. I want to see if it is the same issue that my friend experienced. Thank you

**Comment by Cyb3rWard0g** [comment]
@alijnclarke issues with the subnet interfering with your local subnet or the docker already defined network???

**Comment by alijnclarke** [comment]
docker subnet interfering with the local, i managed to delete the docker network and recreate using a different subnet, but had more issues with things like kibana not working :( 

hopefully manage to fix soon :D

**Comment by Cyb3rWard0g** [comment]
Ok . I am pushing an update this weekend and that should not rely on static hardcoded IP addresses. containers will talk to each other via its own service name.

**Comment by alijnclarke** [comment]
awesome news! when do you think you'll be able to push that update @Cyb3rWard0g ?

**Comment by Cyb3rWard0g** [comment]
@alijnclarke check the update and see if that helps. The Build does not set any static IP configurations anymore. However, this does not mean that it will not conflict with with other subnets since the containers still get an IP assigned to them. Now, the container IPs of course do cannot be reached outside of the containers so I dont think it will be a problem. Check it out and let me know.

**Comment by Cyb3rWard0g** [comment]
Hey @alijnclarke! Let me know if the update helped. Thank you

**Comment by TDominiqueWilliams** [comment]
@Cyb3rWard0g I am sorry for the delay in my response, I have been traveling for work. I did a fresh install of your updated HELK and it ran smoothly. It looks like your fix by eliminating the subnets works.

**Comment by Cyb3rWard0g** [comment]
Thank you very much for the update 👍
