### ISSUE TITLE
Minimum Disk Space Requirement 

### ISSUE THREAD

**Issue by bfuzzy** [Cyb3rWard0g/HELK#44]
Hey @Cyb3rWard0g , 

During our testing / me breaking HELK last week. We kept getting that weird ElasticSearch error, which I don't recall off the top of my head but it was related to disk size. 

Having  the minimum requirement documented for disk space to 50gb for testing purposes and 100gb+ for production should meet minimum requirements on the disk space issue. 

Secondly, you could look at further optimization of ElasticSearch to fine tune the disk usage [https://www.elastic.co/guide/en/elasticsearch/reference/6.2/tune-for-disk-usage.html](url) shows some good information on how that can be done through ElasticSearch.

**Comment by Cyb3rWard0g** [comment]
Thats awesome @bfuzzy !!! Yes thank you very much for providing the details and sharing the link 👍  I will add that to the wiki. Thank you

**Comment by Cyb3rWard0g** [comment]
I use the https://www.elastic.co/guide/en/elasticsearch/reference/6.2/multi-fields.html option in my templates to allow full text search (text) and filtering (Keyword). The other ones are very interesting.
* I set the text norms to false too on all my dynamic templates.
* I will take a look at the best_compression & max_num_segments=1

Thank you. I will close this issue since the wiki has been updated to reflect the disk minimum requirements : https://github.com/Cyb3rWard0g/HELK/wiki/Installation
