### ISSUE TITLE
heapspace calc sets to zero

### ISSUE THREAD

**Issue by dtpryce** [Cyb3rWard0g/HELK#47]
When trying to start up Elasticsearch using the entrypoint script noticed an error around incorrect heapspace and double checked. It was in fact setting -Xmx to 0g so was not able to start the service. Had to change to 1g and restart image to get URI etc. 
<img width="636" alt="screen shot 2018-04-30 at 16 19 43" src="https://user-images.githubusercontent.com/2737000/39435098-67dc453a-4c92-11e8-8031-3983ac0b0a98.png">

**Comment by Cyb3rWard0g** [comment]
Hey @dtpryce if the HEAP SIZE was set to zero, that means that you dont have enough memory. The current elasticsearch entrypoint script grabs your available memory and then gets half of it.

![image](https://user-images.githubusercontent.com/9653181/39481742-6fee6eda-4d3a-11e8-940c-eebe9a7318e5.png)

expr does not round up the number so if the result is 3.7 it brings it down to 3. If you got zero is because the result was between 0-1g. 

How much memory are you assigning to your box. In the wiki, I recommend at least 16GB.

https://github.com/Cyb3rWard0g/HELK/wiki/Installation

I am pushing an update soon where the installation script will first check the resources applied tothe box. if it does not pass the minimum requirements then it will stop the installation. 

Let me know if this makes sense. Thank you!

**Comment by dtpryce** [comment]
Totally makes sense and a good idea to check the system resources.

I was using it locally which probably didn't have enough resource tbf. Now running in cloud and all fine. Just trying to switch out some services now for my own ;)

Thanks for the quick and clear response. Will be following with interest!

**Comment by Cyb3rWard0g** [comment]
Thank you for the update @dtpryce !! Yeah it happens. Im pushing an update in the next few minutes that I worked on last night. That now asks you for at least 12GB and 50GB of disk as minimum requirements. 👍 I will close this issue when I push the updated

**Comment by Cyb3rWard0g** [comment]
@dtpryce I just pushed this update https://github.com/Cyb3rWard0g/HELK/commit/10de1b6b0ae9437c0d5e3b888ac819b08a73eee7 . That should address the verification of memory and disk before installation. Thank you! 👍
