### ISSUE TITLE
Error : Elasticsearch port isn't open .

### ISSUE THREAD

**Issue by htoochonaung** [Cyb3rWard0g/HELK#477]
After i finished installation, all containers are running .Kibana dashboard is running.but when i check local port 
netstat -aon 

elasticsearch's port isn't open .

![image](https://user-images.githubusercontent.com/46007529/85838010-ead94c00-b7be-11ea-914e-1b721e5c6f72.png)

So, I can't add the elasticsearch port in client's filebeat .like 
host [" ip : port"]

**Comment by Cyb3rWard0g** [comment]
Hey @htoochonaung , HELK is built to not expose ES port since that is not best practices. We encourage to use the `Kafka-Logstash-ES` or `Logstash-ES` data pipelines. However, you can expose ES port yourself if you wanted to. You would just have to modify the `docker-compose` file that you used to build HELK. I would do something similar to what we do for Logstash. This is an example of the basic template: https://github.com/Cyb3rWard0g/HELK/blob/master/docker/helk-kibana-analysis-basic.yml#L58-L67 . Let me know if this helps.

**Comment by Nicole1122** [comment]
Hey, this didn't work out for me. I added the 9200 port to this section and ran the docker installation. The port was still closed. what did I do wrong?

**Comment by Cyb3rWard0g** [comment]
what dockerfile did you update and what HELK install option did you use? 1-4?
